/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#d3e4fe",
        "accent-emerald": "#10B981",
        "primary": "#3525cd",
        "on-surface-variant": "#464555",
        "on-primary-fixed": "#0f0069",
        "border-strong": "#CBD5E1",
        "on-error-container": "#93000a",
        "on-background": "#0b1c30",
        "surface": "#f8f9ff",
        "tertiary-fixed-dim": "#4edea3",
        "canvas-slate": "#F8FAFC",
        "secondary-fixed": "#dae2fd",
        "on-tertiary-container": "#67f4b7",
        "brand-indigo-light": "#EEF2FF",
        "outline-variant": "#c7c4d8",
        "surface-bright": "#f8f9ff",
        "background": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#dce9ff",
        "secondary": "#565e74",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#002113",
        "brand-indigo-hover": "#3730A3",
        "surface-white": "#FFFFFF",
        "tertiary-container": "#006e4b",
        "surface-container": "#e5eeff",
        "error": "#ba1a1a",
        "inverse-on-surface": "#eaf1ff",
        "surface-dim": "#cbdbf5",
        "secondary-fixed-dim": "#bec6e0",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#c3c0ff",
        "inverse-surface": "#213145",
        "surface-tint": "#4d44e3",
        "on-tertiary-fixed-variant": "#005236",
        "on-primary-container": "#dad7ff",
        "text-secondary": "#334155",
        "text-muted": "#64748B",
        "primary-fixed": "#e2dfff",
        "tertiary-fixed": "#6ffbbe",
        "on-surface": "#0b1c30",
        "on-secondary-fixed-variant": "#3f465c",
        "tertiary": "#005338",
        "on-primary-fixed-variant": "#3323cc",
        "accent-rose-subtle": "#FEF2F2",
        "on-tertiary": "#ffffff",
        "accent-amber": "#F59E0B",
        "border-subtle": "#E2E8F0",
        "surface-container-highest": "#d3e4fe",
        "secondary-container": "#dae2fd",
        "surface-container-low": "#eff4ff",
        "primary-container": "#4f46e5",
        "on-error": "#ffffff",
        "whatsapp-green": "#25D366",
        "text-primary": "#0F172A",
        "outline": "#777587",
        "accent-amber-subtle": "#FFFBEB",
        "accent-rose": "#EF4444",
        "inverse-primary": "#c3c0ff",
        "accent-emerald-subtle": "#ECFDF5",
        "on-secondary-fixed": "#131b2e",
        "on-primary": "#ffffff",
        "on-secondary-container": "#5c647a",
        "brand-indigo-deep": "#1E1B4B"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
      fontFamily: {
        "sans": ["var(--font-inter)", "system-ui", "-apple-system", "sans-serif"],
        "title-md": ["var(--font-jakarta)", "sans-serif"],
        "display-hero": ["var(--font-jakarta)", "sans-serif"],
        "metric-display": ["var(--font-jakarta)", "sans-serif"],
        "headline-lg": ["var(--font-jakarta)", "sans-serif"],
        "label-lg": ["var(--font-inter)", "sans-serif"],
        "body-sm": ["var(--font-inter)", "sans-serif"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "headline-sm": ["var(--font-jakarta)", "sans-serif"],
        "label-sm": ["var(--font-inter)", "sans-serif"],
        "headline-md": ["var(--font-jakarta)", "sans-serif"],
        "headline-xl": ["var(--font-jakarta)", "sans-serif"],
        "label-md": ["var(--font-inter)", "sans-serif"]
      }
    }
  },
  plugins: [],
};
